# Description:
#   Play Cards Against Humanity in Hubot
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   q card - Returns a question
#   card me - Displays an answer
#   card 2 - Displays two answers for questions with two blanks
#
# Author:
#   Jonny Campbell (@jonnycampbell)

questions = [
"Air Canada guidelines now prohibit ____ on airplanes.",
 "O Canada, we stand on guard for ____.",
 "CTV presents ____, the story of ____.",
 "In an attempt to reach a wider audience, the Royal Ontario Museum has opened an interactive exhibit on ____.",
 "What's the Canadian government using to inspire rural students to succeed?",
 "Daddy, why is Mommy crying?",
 "What brought the orgy to a grinding halt?",
 "When I pooped, what came out of my butt?",
 "In the distant future, historians will agree that ____ marked the beginning of America's decline.",
 "What's the gift that keeps on giving?",
 "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only ____ and his wits.",
 "Michael Bay's new three-hour action epic pits ____ against ____.",
 "And I would have gotten away with i1, too, if it hadn't been for ____!",
 "In a pinch, ____ can be a suitable substitute for ____.",
 "What has been making life difficult at the nudist colony?",
 "Science will never explain the origin of ____.",
 "In Rome, there are whisperings that the Vatican has a secret room devoted to ____.",
 "I learned the hard way that you can't cheer up a grieving friend with ____.",
 "When all else fails, I can always masturbate to ____.",
 "An international tribunal has found ____ guilty of ____.",
 "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ____.",
 "In his new self-produced album, Kanye West raps over the sounds of ____.",
 "The socialist governments of Scandinavia have declared that access to ____ is a basic human right.",
 "He who controls ____ controls the world.",
 "Dear Sir or Madam, We regret to inform you that the Office of ____ has denied your request for ____.",
 "The CIA now interrogates enemy agents by repeatedly subjecting them to ____.",
 "____ would be woefully incomplete without ____.",
 "During his midlife crisis, my dad got really into ____.",
 "Before I run for presiden1, I must destroy all evidence of my involvement with ____.",
 "My new favorite porn star is Joey \"____\" McGee.",
 "In his newest and most difficult stun1, David Blaine must escape from ____.",
 "This is your captain speaking. Fasten your seatbelts and prepare for ____.",
 "My mom freaked out when she looked at my browser history and found ____.com/____.",
 "The Five Stages of Grief: denial, anger, bargaining, ____, acceptance.",
 "Members of New York's social elite are paying thousands of dollars just to experience ____.",
 "I went from ____ to ____, all thanks to ____.",
 "Little Miss Muffet Sat on a tuffe1, Eating her curds and ____.",
 "This month's Cosmo: \"Spice up your sex life by bringing ____ into the bedroom.\"",
 "If God didn't want us to enjoy ____, he wouldn't have given us ____.",
 "My country, 'tis of thee, sweet land of ____.",
 "After months of debate, the Occupy Wall Street General Assembly could only agree on \"More ____!\"",
 "I spent my whole life working toward ____, only to have it ruined by ____.",
 "Next time on Dr. Phil: How to talk to your child about ____.",
 "Only two things in life are certain: death and ____.",
 "Everyone down on the ground! We don't want to hurt anyone. We're just here for ____.",
 "The healing process began when I joined a support group for victims of ____.",
 "The votes are in, and the new high school mascot is ____.",
 "Charades was ruined for me forever when my mom had to act out ____.",
 "Before ____, all we had was ____.",
 "Tonight on 20/20: What you don't know about ____ could kill you.",
 "You haven't truly lived until you've experienced ____ and ____ at the same time.",
 "After blacking out during New Year's Eve, I was awoken by ____.",
 "This holiday season, Tim Allen must overcome his fear of ____ to save Christmas.",
 "Jesus is ____.",
 "Every Christmas, my uncle gets drunk and tells the story about ____.",
 "What keeps me warm during the cold, cold winter?",
 "On the third day of Christmas, my true love gave to me: three French hens, two turtle doves, and ____.",
 "Wake up, America. Christmas is under attack by secular liberals and their ____.",
 "Hey baby, come back to my place and I'll show you ____.",
 "My gym teacher got fired for adding ____ to the obstacle course.",
 "Finally! A service that delivers ____ right to your door.",
 "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ____.",
 "My life is ruled by a vicious cycle of ____ and ____.",
 "During high school, I never really fit in until I found ____ club.",
 "Money can't buy me love, but it can buy me ____.",
 "Listen, son. If you want to get involved with ____, I won't stop you. Just steer clear of ____.",
 "A successful job interview begins with a firm handshake and ends with ____.",
 "Call the law offices of Goldstein &amp; Goldstein, because no one should have to tolerate ____ in the workplace.",
 "Lovin' you is easy 'cause you're ____.",
 "The blind date was going horribly until we discovered our shared interest in ____.",
 "What left this stain on my couch?",
 "Turns out that ____-Man was neither the hero we needed nor wanted.",
 "After months of practice with ____, I think I'm finally ready for ____.",
 "In the seventh circle of Hell, sinners must endure ____ for all eternity.",
 "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ____.",
 "When you get right down to i1, ____ is just ____.",
 "Having problems with ____? Try ____!",
 "And what did <i>you</i> bring for show and tell?",
 "I'm not like the rest of you. I'm too rich and busy for ____.",
 "With enough time and pressure, ____ will turn into ____.",
 "____: Hours of fun. Easy to use. Perfect for ____!",
 "____. Awesome in theory, kind of a mess in practice.",
 "As part of his contrac1, Prince won't perform without ____ in his dressing room.",
 "During his childhood, Salvador Dal&iacute; produced hundreds of paintings of ____.",
 "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
 "What don't you want to find in your Kung Pao chicken?",
 "Here is the church<br>Here is the steeple<br>Open the doors<br>And there is ____.",
 "How did I lose my virginity?",
 "Why can't I sleep at night?",
 "I got 99 problems but ____ ain't one.",
 "What's a girl's best friend?",
 "What's that smell?",
 "This is the way the world ends \\ This is the way the world ends \\ Not with a bang but with ____.",
 "What is Batman's guilty pleasure?",
 "TSA guidelines now prohibit ____ on airplanes.",
 "What ended my last relationship?",
 "And the Academy Award for ____ goes to ____.",
 "MTV's new reality show features eight washed-up celebrities living with ____.",
 "For my next trick, I will pull ____ out of ____.",
 "I drink to forget ____.",
 "I'm sorry, Professor, but I couldn't complete my homework because of ____.",
 "Alternative medicine is now embracing the curative powers of ____.",
 "What's that sound?",
 "What's the next Happy Meal&reg; toy?",
 "It's a pity that kids these days are all getting involved with ____.",
 "In M. Night Shyamalan's new movie, Bruce Willis discovers that ____ had really been ____ all along.",
 "In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.",
 "____ is a slippery slope that leads to ____.",
 "____. That's how I want to die.",
 "In a world ravaged by ____, our only solace is ____.",
 "What does Dick Cheney prefer?",
 "What's the next superhero/sidekick duo?",
 "What's the most emo?",
 "Dear Abby,<br><br>I'm having some trouble with ____ and would like your advice.",
 "Instead of coal, Santa now gives the bad children ____.",
 "Next from J.K. Rowling: Harry Potter and the Chamber of ____.",
 "A romantic, candlelit dinner would be incomplete without ____.",
 "Maybe she's born with it. Maybe it's ____.",
 "White people like ____.",
 "____. Betcha can't have just one!",
 "War!<br><br>What is it good for?",
 "BILLY MAYS HERE FOR ____.",
 "____. High five, bro.",
 "During sex, I like to think about ____.",
 "What did I bring back from Mexico?",
 "What are my parents hiding from me?",
 "What will always get you laid?",
 "What would grandma find disturbing, yet oddly charming?",
 "What did the U.S. airdrop to the children of Afghanistan?",
 "What helps Obama unwind?",
 "What's there a ton of in heaven?",
 "Major League Baseball has banned ____ for giving players an unfair advantage.",
 "When I am a billionare, I shall erect a 50-foot statue to commemorate ____.",
 "What's the new fad diet?",
 "When I am the President of the United States, I will create the Department of ____.",
 "____. It's a trap!",
 "How am I maintaining my relationship status?",
 "What will I bring back in time to convince people that I am a powerful wizard?",
 "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ____.",
 "Coming to Broadway this season, ____: The Musical.",
 "What's my secret power?",
 "What gives me uncontrollable gas?",
 "But before I kill you, Mr. Bond, I must show you ____.",
 "What never fails to liven up the party?",
 "What am I giving up for Lent?",
 "What do old people smell like? ",
 "The class field trip was completely ruined by ____.",
 "When Pharaoh remained unmoved, Moses called down a plague of ____.",
 "Daddy, why is Mommy crying?",
 "I do not know with which weapons World War III will be fough1, but World War IV will be fought with ____.",
 "What's Teach for America using to inspire inner city students to succeed?",
 "In Michael Jackson's final moments, he thought about ____.",
 "Why do I hurt all over?",
 "Studies show that lab rats navigate mazes 50% faster after being exposed to ____.",
 "Why am I sticky?",
 "What's my anti-drug?",
 "____: Good to the last drop.",
 "What did Vin Diesel eat for dinner?",
 "____: kid-tested, mother-approved.",
 "What gets better with age?",
 "I never truly understood ____ until I encountered ____.",
 "Rumor has it that Vladimir Putin's favorite delicacy is ____ stuffed with ____.",
 "Lifetime&reg; presents ____, the story of ____.",
 "Make a haiku.",
 "After the earthquake, Sean Penn brought ____ to the people of Haiti.",
 "In L.A. County Jail, word is you can trade 200 cigarettes for ____.",
 "That's righ1, I killed ____. How, you ask? ____.",
 "When I was tripping on acid, ____ turned into ____.",
 "____ + ____ = ____.",
 "Life for American Indians was forever changed when the White Man introduced them to ____.",
 "Next on ESPN2, the World Series of ____.",
 "Step 1: ____. Step 2: ____. Step 3: Profit.",
 "The Smithsonian Museum of Natural History has just opened an exhibit on ____."
 ]

answers = [
"Poutine.",
 "Newfies.",
 "The Official Languages Act. La Loi sur les langues officielles.",
 "Terry Fox's prosthetic leg.",
 "The FLQ.",
 "Canada: America's Hat.",
 "Don Cherry's wardrobe.",
 "Burning down the White House.",
 "Heritage minutes.",
 "Homo milk.",
 "Naked News.",
 "Mr. Dressup.",
 "Syrupy sex with a maple tree.",
 "Being Canadian.",
 "Snotsicles.",
 "The Famous Five.",
 "Schmirler the Curler.",
 "Stephen Harper.",
 "A Molson muscle.",
 "The Royal Canadian Mounted Police.",
 "An icy handjob from an Edmonton hooker.",
 "A bitch slap.",
 "One trillion dollars.",
 "Chunks of dead prostitute.",
 "The entire Mormon Tabernacle Choir.",
 "The female orgasm.",
 "Extremely tight pants.",
 "The Boy Scouts of America.",
 "Stormtroopers.",
 "Throwing a virgin into a volcano.",
 "Getting in her pants, politely.",
 "Gladiatorial combat.",
 "Good grammar.",
 "Hipsters.",
 "Gandalf.",
 "Genetically engineered super-soldiers.",
 "George Clooney's musk.",
 "Getting abducted by Peter Pan.",
 "Eating an albino.",
 "Enormous Scandinavian women.",
 "Fabricating statistics.",
 "Finding a skeleton.",
 "Suicidal thoughts.",
 "Dancing with a broom.",
 "Deflowering the princess.",
 "Dorito breath.",
 "One thousand Slim Jims.",
 "My machete.",
 "Overpowering your father.",
 "Ominous background music.",
 "Media coverage.",
 "Making the penises kiss.",
 "Moral ambiguity.",
 "Medieval Times&reg; Dinner &amp; Tournament.",
 "Mad hacky-sack skills.",
 "Just the tip.",
 "Literally eating shit.",
 "Leveling up.",
 "Insatiable bloodlust.",
 "Historical revisionism.",
 "Jean-Claude Van Damme.",
 "Jafar.",
 "The boners of the elderly.",
 "The economy.",
 "Statistically validated stereotypes.",
 "Sudden Poop Explosion Disease.",
 "Slow motion.",
 "Space muffins.",
 "Sexual humiliation.",
 "Sexy Siamese twins.",
 "Santa Claus.",
 "Scrotum tickling.",
 "Ripping into a man's chest and pulling out his still-beating heart.",
 "Ryan Gosling riding in on a white horse.",
 "Quivering jowls.",
 "Revenge fucking.",
 "Pistol-whipping a hostage.",
 "Quiche.",
 "Zeus's sexual appetites.",
 "Words, words, words.",
 "Tripping balls.",
 "Being a busy adult with many important things to do.",
 "The four arms of Vishnu.",
 "The shambling corpse of Larry King.",
 "The hiccups.",
 "The harsh light of day.",
 "The Gulags.",
 "The Fanta&reg; girls.",
 "A big black dick.",
 "A beached whale.",
 "A low standard of living.",
 "A nuanced critique.",
 "A bloody pacifier.",
 "A crappy little hand.",
 "Shaft.",
 "Being a dinosaur.",
 "Beating your wives.",
 "Neil Patrick Harris.",
 "Coughing into a vagina.",
 "Carnies.",
 "Nubile slave boys.",
 "Bosnian chicken farmers.",
 "A web of lies.",
 "A rival dojo.",
 "A passionate Latino lover.",
 "Panty raids.",
 "Appreciative snapping.",
 "Apologizing.",
 "Clams.",
 "A woman scorned.",
 "Being awesome at sex.",
 "Spring break!",
 "Another shot of morphine.",
 "Dining with cardboard cutouts of the cast of \"Friends.\"",
 "A soulful rendition of \"Ol' Man River.\"",
 "Making a friend.",
 "A sweaty, panting leather daddy.",
 "Intimacy problems.",
 "The new Radiohead album.",
 "Pretty Pretty Princess Dress-Up Board Game&reg;.",
 "A man in yoga pants with a ponytail and feather earrings.",
 "An army of skeletons.",
 "A squadron of moles wearing aviator goggles.",
 "Beefin' over turf.",
 "The Google.",
 "Bullshit.",
 "A sweet spaceship.",
 "A 55-gallon drum of lube.",
 "Special musical gues1, Cher.",
 "The human body.",
 "Mild autism.",
 "Nunchuck moves.",
 "Whipping a disobedient slave.",
 "An ether-soaked rag.",
 "Oncoming traffic.",
 "A dollop of sour cream.",
 "A slightly shittier parallel universe.",
 "My first kill.",
 "Boris the Soviet Love Hammer.",
 "The grey nutrient broth that sustains Mitt Romney.",
 "Tiny nipples.",
 "Power.",
 "Death by Steven Seagal.",
 "A Burmese tiger pit.",
 "Basic human decency.",
 "Grandpa's ashes.",
 "One Ring to rule them all.",
 "The day the birds attacked.",
 "Fetal alcohol syndrome.",
 "Graphic violence, adult language, and some sexual content.",
 "A bigger, blacker dick.",
 "The mere concept of Applebee's&reg;.",
 "A sad fat dragon with no friends.",
 "A pi&ntilde;ata full of scorpions.",
 "Existing.",
 "Hillary Clinton's death stare.",
 "Catastrophic urethral trauma.",
 "Double penetration.",
 "Daddy's belt.",
 "Swiftly achieving orgasm.",
 "Mooing.",
 "Rising from the grave.",
 "Subduing a grizzly bear and making her your wife.",
 "Some really fucked-up shit.",
 "Weapons-grade plutonium.",
 "All of this blood.",
 "Scrotal frostbite.",
 "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.",
 "The mixing of the races.",
 "Pumping out a baby every nine months.",
 "Tongue.",
 "Loki, the trickster god.",
 "Whining like a little bitch.",
 "Wearing an octopus for a hat.",
 "An unhinged ferris wheel rolling toward the sea.",
 "Finding Waldo.",
 "Upgrading homeless people to mobile hotspots.",
 "A magic hippie love cloud.",
 "Fuck Mountain.",
 "Living in a trashcan.",
 "The corporations.",
 "Getting hilariously gang-banged by the Blue Man Group.",
 "Jeff Goldblum.",
 "Survivor's guilt.",
 "Me.",
 "Santa's heavy sack.",
 "Clearing a bloody path through Walmart with a scimitar.",
 "Another shitty year.",
 "Whatever Kwanzaa is supposed to be about.",
 "A Christmas stocking full of coleslaw.",
 "Elf cum.",
 "The tiny, calloused hands of the Chinese children that made this card.",
 "Taking down Santa with a surface-to-air missle.",
 "Several intertwining love stories featuring Hugh Grant.",
 "Mall Santa.",
 "My hot cousin.",
 "The Star Wars Holiday Special.",
 "Krampus, the Austrian Christmas monster.",
 "Pretending to be happy.",
 "Socks. ",
 "Eating an entire snowman.",
 "A toxic family environment.",
 "A visually arresting turtleneck.",
 "Fucking up \"Silent Night\" in front of 300 parents.",
 "Immaculate conception.",
 "Space Jam on VHS.",
 "Gift-wrapping a live hamster.",
 "A Hungry-Man&trade; Frozen Christmas Dinner for One.",
 "All my friends dying.",
 "Shutting the fuck up.",
 "An ass disaster.",
 "Some kind of bird-man.",
 "The entire Internet.",
 "Going around punching people.",
 "A boo-boo.",
 "Indescribable loneliness.",
 "Having sex on top of a pizza.",
 "Chugging a lava lamp.",
 "Warm, velvety muppet sex.",
 "Running naked through a mall, pissing and shitting everywhere.",
 "Nothing.",
 "Samuel L. Jackson.",
 "Self-flagellation.",
 "The systematic destruction of an entire people and their way of life.",
 "The Quesadilla Explosion Salad&trade; from Chili's&reg;.",
 "Reverse cowgirl.",
 "Vietnam flashbacks.",
 "Actually getting sho1, for real.",
 "Not having sex.",
 "Cock.",
 "Dying alone and in pain.",
 "A cop who is also a dog.",
 "The way white people is.",
 "Gay aliens.",
 "The primal, ball-slapping sex your parents are having right now.",
 "A cat video so cute that your eyes roll back and your spine slides out of your anus.",
 "A lamprey swimming up the toilet and latching onto your taint.",
 "Slapping a racist old lady.",
 "A black male in his early 20s, last seen wearing a hoodie.",
 "Jumping out at people.",
 "Three months in the hole.",
 "Blood farts.",
 "The Land of Chocolate.",
 "A botched circumcision.",
 "My manservan1, Claude.",
 "Vomiting mid-blowjob.",
 "Letting everyone down.",
 "Having shotguns for legs.",
 "Bill Clinton, naked on a bearskin rug with a saxophone.",
 "Mufasa's death scene.",
 "The Harlem Globetrotters.",
 "Demonic possession.",
 "Fisting.",
 "The thin veneer of situational causality that underlies porn.",
 "Girls that always be textin'.",
 "Blowing some dudes in an alley.",
 "A spontaneous conga line.",
 "A vagina that leads to another dimension.",
 "Disco fever.",
 "Getting your dick stuck in a Chinese finger trap with another dick.",
 "Drinking ten 5-hour ENERGYs&reg; to get fifty continuous hours of energy.",
 "Sneezing, farting, and coming at the same time.",
 "Some douche with an acoustic guitar.",
 "Spending lots of money.",
 "Putting an entire peanut butter and jelly sandwich into the VCR.",
 "An unstoppable wave of fire ants.",
 "A greased-up Matthew McConaughey.",
 "Flying robots that kill people.",
 "Unlimited soup, salad, and breadsticks.",
 "Crying into the pages of Sylvia Plath.",
 "The mois1, demanding chasm of his mouth.",
 "Filling every orifice with butterscotch pudding.",
 "An all-midget production of Shakespeare's <i>Richard III</i>.",
 "Screaming like a maniac.",
 "Not contributing to society in any meaningful way.",
 "A pile of squirming bodies.",
 "Buying the right pants to be cool.",
 "Roland the Farter, flatulist to the king.",
 "That ass.",
 "A surprising amount of hair.",
 "Eating Tom Selleck's mustache to gain his powers.",
 "Velcro&trade;.",
 "A PowerPoint presentation.",
 "A bucket of fish heads.",
 "50,000 volts straight to the nipples.",
 "Being fat and stupid.",
 "Hospice care.",
 "A pyramid of severed heads.",
 "Getting married, having a few kids, buying some stuf0, retiring to Florida, and dying.",
 "A subscription to Men's Fitness.",
 "Crucifixion.",
 "A micropig wearing a tiny raincoat and booties.",
 "Some god-damn peace and quiet.",
 "Used panties.",
 "A tribe of warrior women.",
 "The penny whistle solo from \"My Heart Will Go On.\"",
 "Funky fresh rhymes.",
 "The art of seduction.",
 "The Devil himself.",
 "Advice from a wise, old black man.",
 "Destroying the evidence.",
 "The light of a billion suns.",
 "Wet dreams.",
 "Synergistic management solutions.",
 "Growing a pair.",
 "Silence.",
 "An M16 assault rifle.",
 "Poopy diapers.",
 "A live studio audience.",
 "The Great Depression.",
 "A spastic nerd.",
 "Rush Limbaugh's sof1, shitty body.",
 "Tickling Sean Hannity, even after he tells you to stop.",
 "Stalin.",
 "Brown people.",
 "Rehab.",
 "Capturing Newt Gingrich and forcing him to dance in a monkey suit.",
 "Battlefield amputations.",
 "An uppercut.",
 "Shiny objects.",
 "An ugly face.",
 "Menstrual rage.",
 "Roofies.",
 "Women in yogurt commercials.",
 "A windmill full of corpses.",
 "Old-people smell.",
 "Being on fire.",
 "A micropenis.",
 "Sexting.",
 "Classist undertones.",
 "Not giving a shit about the Third World.",
 "The gays.",
 "Racism.",
 "Free samples.",
 "Sexual tension.",
 "Figgy pudding.",
 "An oversized lollipop.",
 "Five-Dollar Footlongs&trade;.",
 "Barack Obama.",
 "Genital piercings.",
 "A tiny horse.",
 "Elderly Japanese men.",
 "A stray pube.",
 "The Tempur-Pedic&reg; Swedish Sleep System&trade;.",
 "Bingeing and purging.",
 "A bag of magic beans.",
 "An asymmetric boob job.",
 "Famine.",
 "African children.",
 "Heartwarming orphans.",
 "Boogers.",
 "Men.",
 "Dry heaving.",
 "My humps.",
 "The hardworking Mexican.",
 "An Oedipus complex.",
 "Darth Vader.",
 "Skeletor.",
 "Scientology.",
 "Estrogen.",
 "Penis envy.",
 "Pictures of boobs.",
 "Pedophiles.",
 "Pabst Blue Ribbon.",
 "The Pope.",
 "Prancing.",
 "Repression.",
 "Overcompensation.",
 "Being fabulous.",
 "My relationship status.",
 "Eating all of the cookies before the AIDS bake-sale.",
 "Dick Cheney.",
 "Lance Armstrong's missing testicle.",
 "The Amish.",
 "Pooping back and forth. Forever.",
 "MechaHitler.",
 "Peeing a little bit.",
 "The World of Warcraft.",
 "Testicular torsion.",
 "A gentle caress of the inner thigh.",
 "Explosions.",
 "Sarah Palin.",
 "Amputees.",
 "Being marginalized.",
 "The Blood of Christ.",
 "Bitches.",
 "Italians.",
 "Dead parents.",
 "Dying of dysentery.",
 "Sexy pillow fights.",
 "Civilian casualties.",
 "The female orgasm.",
 "Auschwitz.",
 "Agriculture.",
 "The Boy Scouts of America.",
 "Throwing a virgin into a volcano.",
 "The Jews.",
 "Judge Judy.",
 "Surprise sex!",
 "The Virginia Tech Massacre.",
 "Scrubbing under the folds.",
 "An M. Night Shyamalan plot twist.",
 "Mr. Clean, right behind you.",
 "Cybernetic enhancements.",
 "Feeding Rosie O'Donnell.",
 "The Trail of Tears.",
 "Finger painting.",
 "The Care Bear Stare.",
 "Jewish fraternities.",
 "The homosexual agenda.",
 "Flying sex snakes.",
 "Natalie Portman.",
 "Another goddamn vampire movie.",
 "Hot Pockets&reg;.",
 "Robert Downey, Jr.",
 "A good sniff.",
 "My soul.",
 "Fingering.",
 "Horse meat.",
 "Crippling debt.",
 "Praying the gay away.",
 "German dungeon porn.",
 "Heteronormativity.",
 "Dying.",
 "One trillion dollars.",
 "The invisible hand.",
 "A really cool hat.",
 "Justin Bieber.",
 "YOU MUST CONSTRUCT ADDITIONAL PYLONS.",
 "A sausage festival.",
 "Michael Jackson.",
 "Police brutality.",
 "Teaching a robot to love.",
 "Catapults.",
 "A disappointing birthday party.",
 "Balls.",
 "Dental dams.",
 "Powerful thighs.",
 "Serfdom.",
 "Children on leashes.",
 "Friends with benefits.",
 "RoboCop.",
 "Copping a feel.",
 "Shapeshifters.",
 "Teenage pregnancy.",
 "All-you-can-eat shrimp for $4.99.",
 "Getting naked and watching Nickelodeon.",
 "The Holy Bible.",
 "Kamikaze pilots.",
 "My inner demons.",
 "Crystal meth.",
 "Eugenics.",
 "The chronic.",
 "Man meat.",
 "The violation of our most basic human rights.",
 "Smegma.",
 "A bleached asshole.",
 "Stranger danger.",
 "The terrorists.",
 "Same-sex ice dancing.",
 "Making a pouty face.",
 "Object permanence.",
 "The Three-Fifths compromise.",
 "Sunshine and rainbows.",
 "Emotions.",
 "Necrophilia.",
 "Panda sex.",
 "Whipping it out.",
 "The token minority.",
 "That thing that electrocutes your abs.",
 "Fiery poops.",
 "Picking up girls at the abortion clinic.",
 "Vehicular manslaughter.",
 "Lockjaw.",
 "Attitude.",
 "A snapping turtle biting the tip of your penis.",
 "Public ridicule.",
 "Stephen Hawking talking dirty.",
 "Tangled Slinkys.",
 "Grave robbing.",
 "GoGurt&reg;.",
 "Passable transvestites.",
 "Muhammed (Praise Be Unto Him).",
 "Getting so angry that you pop a boner.",
 "Multiple stab wounds.",
 "The Dance of the Sugar Plum Fairy.",
 "A monkey smoking a cigar.",
 "Unfathomable stupidity.",
 "Firing a rifle into the air while balls deep in a squealing hog.",
 "Self-loathing.",
 "Geese.",
 "A thermonuclear detonation.",
 "The American Dream.",
 "God.",
 "Hurricane Katrina.",
 "A brain tumor.",
 "Lactation.",
 "Kids with ass cancer.",
 "New Age music.",
 "Lumberjack fantasies.",
 "Puberty.",
 "Kanye West.",
 "Harry Potter erotica.",
 "Dead babies.",
 "The true meaning of Christmas.",
 "Nickelback.",
 "The South.",
 "Opposable thumbs.",
 "Preteens.",
 "Land mines.",
 "Authentic Mexican cuisine.",
 "Swee1, sweet vengeance.",
 "Me time.",
 "Saxophone solos.",
 "Guys who don't call.",
 "The taint; the grundle; the fleshy fun-bridge.",
 "Winking at old people.",
 "Oompa-Loompas.",
 "Parting the Red Sea.",
 "Ghosts.",
 "The Little Engine That Could.",
 "Vigilante justice.",
 "Erectile dysfunction.",
 "Fear itself.",
 "William Shatner.",
 "A falcon with a cap on its head.",
 "Chunks of dead prostitute.",
 "Vikings.",
 "Farting and walking away.",
 "The Chinese gymnastics team.",
 "Yeast.",
 "Leaving an awkward voicemail.",
 "White people.",
 "Sperm whales.",
 "A sassy black woman.",
 "Friction.",
 "A can of whoop-ass.",
 "A murder most foul.",
 "The inevitable heat death of the universe.",
 "Being a motherfucking sorcerer.",
 "Daddy issues.",
 "Gloryholes.",
 "A time travel paradox.",
 "Poorly-timed Holocaust jokes.",
 "Licking things to claim them as your own.",
 "Republicans.",
 "A mating display.",
 "A mime having a stroke.",
 "Asians who aren't good at math.",
 "Alcoholism.",
 "The Kool-Aid Man.",
 "Tentacle porn.",
 "Lunchables&trade;.",
 "AXE Body Spray.",
 "Hot cheese.",
 "A mopey zoo lion.",
 "A defective condom.",
 "Actually taking candy from a baby.",
 "Exactly what you'd expect.",
 "Inappropriate yodeling.",
 "Lady Gaga.",
 "Nicolas Cage.",
 "The Big Bang.",
 "Aaron Burr.",
 "Cheating in the Special Olympics.",
 "Foreskin.",
 "Hormone injections.",
 "A sad handjob.",
 "Bling.",
 "Count Chocula.",
 "A sea of troubles.",
 "Christopher Walken.",
 "Waiting 'til marriage.",
 "A cooler full of organs.",
 "Giving 110%.",
 "Pulling out.",
 "Assless chaps.",
 "Dropping a chandelier on your enemies and riding the rope up.",
 "Wearing underwear inside-out to avoid doing laundry.",
 "The glass ceiling.",
 "Adderall&trade;.",
 "Puppies!",
 "Not reciprocating oral sex.",
 "Doin' it in the butt.",
 "A lifetime of sadness.",
 "The Hamburglar.",
 "Obesity.",
 "Tasteful sideboob.",
 "Hot people.",
 "Porn stars.",
 "Two midgets shitting into a bucket.",
 "Nazis.",
 "Getting drunk on mouthwash.",
 "John Wilkes Booth.",
 "The miracle of childbirth.",
 "Soup that is too hot.",
 "The Hustle.",
 "A homoerotic volleyball montage.",
 "Natural male enhancement.",
 "Switching to Geico&reg;.",
 "The Rev. Dr. Martin Luther King, Jr.",
 "Ethnic cleansing.",
 "Extremely tight pants.",
 "The Underground Railroad.",
 "Natural selection.",
 "Taking off your shirt.",
 "Waking up half-naked in a Denny's parking lot.",
 "Smallpox blankets.",
 "Getting really high.",
 "My sex life.",
 "Hope.",
 "A gassy antelope.",
 "Third base.",
 "A Super Soaker&trade; full of cat pee.",
 "White privilege.",
 "Queefing.",
 "Golden showers.",
 "Breaking out into song and dance.",
 "Home video of Oprah sobbing into a Lean Cuisine&reg;.",
 "Autocannibalism.",
 "Helplessly giggling at the mention of Hutus and Tutsis.",
 "Laying an egg.",
 "Chainsaws for hands.",
 "Arnold Schwarzenegger.",
 "An icepick lobotomy.",
 "Goblins.",
 "Pretending to care.",
 "Stormtroopers.",
 "Being rich.",
 "Seppuku.",
 "Toni Morrison's vagina.",
 "Pixelated bukkake.",
 "The folly of man.",
 "Britney Spears at 55.",
 "Ronald Reagan.",
 "Homeless people.",
 "Eating the last known bison.",
 "World peace.",
 "A salty surprise.",
 "72 virgins.",
 "Passing a kidney stone.",
 "Leprosy.",
 "Riding off into the sunset.",
 "My genitals.",
 "Shaquille O'Neal's acting career.",
 "Dick fingers.",
 "A fetus.",
 "BATMAN!!!",
 "Racially-biased SAT questions.",
 "Centaurs.",
 "Grandma.",
 "A Bop It&trade;.",
 "Horrifying laser hair removal accidents.",
 "The Make-A-Wish&reg; Foundation.",
 "A death ray.",
 "Embryonic stem cells.",
 "The profoundly handicapped.",
 "The placenta.",
 "The clitoris.",
 "Sniffing glue.",
 "Spontaneous human combustion.",
 "The KKK.",
 "Flesh-eating bacteria.",
 "Poor people.",
 "The &Uuml;bermensch.",
 "Altar boys.",
 "Black people.",
 "Active listening.",
 "Pac-Man uncontrollably guzzling cum.",
 "My vagina.",
 "Poor life choices.",
 "Coat hanger abortions.",
 "Viagra&reg;.",
 "Spectacular abs.",
 "A balanced breakfast.",
 "Not wearing pants.",
 "Consensual sex.",
 "Former President George W. Bush.",
 "Cuddling.",
 "Science.",
 "Tom Cruise.",
 "The entire Mormon Tabernacle Choir.",
 "Sean Penn.",
 "Historically black colleges.",
 "Sharing needles.",
 "Masturbation.",
 "AIDS.",
 "Gandhi.",
 "A zesty breakfast burrito.",
 "Genghis Khan.",
 "Take-backsies.",
 "Keanu Reeves.",
 "Drinking alone.",
 "Cards Against Humanity.",
 "Edible underpants.",
 "Fancy Feast&reg;.",
 "Passive-agression.",
 "Hulk Hogan.",
 "Sean Connery.",
 "Scalping.",
 "The milk man.",
 "The heart of a child.",
 "Friendly fire.",
 "Jerking off into a pool of children's tears.",
 "Domino's&trade; Oreo&trade; Dessert Pizza.",
 "Half-assed foreplay.",
 "My collection of high-tech sex toys.",
 "A middle-aged man on roller skates.",
 "Bill Nye the Science Guy.",
 "Bees?",
 "8 oz. of sweet Mexican black-tar heroin.",
 "A hot mess.",
 "An erection that lasts longer than four hours.",
 "Wifely duties.",
 "Wiping her butt.",
 "Women's suffrage.",
 "Child beauty pageants.",
 "Expecting a burp and vomiting on the floor.",
 "Morgan Freeman's voice.",
 "Anal beads.",
 "The Force.",
 "Her Majesty, Queen Elizabeth II.",
 "Vigorous jazz hands.",
 "Flightless birds.",
 "Doing the right thing.",
 "Concealing a boner.",
 "A bitch slap.",
 "Raptor attacks.",
 "Being a dick to children.",
 "Mutually-assured destruction.",
 "Nipple blades.",
 "Full frontal nudity.",
 "A foul mouth.",
 "Michelle Obama's arms.",
 "Frolicking.",
 "Mouth herpes.",
 "Incest.",
 "Swooping.",
 "When you fart and a little bit comes out.",
 "A robust mongoloid.",
 "The Rapture.",
 "Road head.",
 "Passive-aggressive Post-it notes."
 ]

module.exports = (robot) ->
  robot.hear /card(?: me)?(?: )(\d+)?/i, (msg) ->
    count = if msg.match[1]? then parseInt(msg.match[1], 10) else 1
    msg.send msg.random answers for i in [1..count]

  robot.hear /q(?:uestion)? card/i, (msg) ->
    msg.send msg.random questions
